// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebook/ent/dialect/sql"
)

// AttendanceGroup is the predicate function for attendancegroup builders.
type AttendanceGroup func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
