CREATE TABLE IF NOT EXISTS users(
   id VARCHAR (20) NOT NULL,
   user_id VARCHAR (80) NOT NULL,
   name VARCHAR (20) NOT NULL,
   password VARCHAR (200) NOT NULL,
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
ALTER TABLE users ADD CONSTRAINT PRIMARY KEY (id);
ALTER TABLE users ADD CONSTRAINT UNIQUE user_index(user_id);