CREATE TABLE IF NOT EXISTS users(
   id VARCHAR (20) NOT NULL,
   login_id VARCHAR (80) NOT NULL,
   name VARCHAR (20),
   password VARCHAR (200) NOT NULL,
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
ALTER TABLE users ADD PRIMARY KEY (id);
ALTER TABLE users ADD UNIQUE user_index(login_id);