version: '3.4'

services:
  https:
    image: steveltn/https-portal
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./resource/certs:/var/lib/https-portal
    environment:
      # FORCE_RENEW: 'true'
      STAGE: local
      DOMAINS: 'attend-manager.localhost -> http://front:3000, api.attend-manager.localhost -> http://api:8080'
    depends_on:
      - api
      - front
    networks:
      - front-link

  front:
    image: attend_manager_front
    build:
      context: .
      dockerfile: ./front/Dockerfile
    volumes:
      - ./front:/app
    networks:
      - front-link
    ports:
      - 3000
    environment:
      API_URL: 'https://api.attend-manager.localhost'
    tty: true

  api:
    image: attend_manager_api
    build:
      context: .
      dockerfile: ./api/Dockerfile
    volumes:
      - ./:/go/app
    networks:
      - api-link
      - front-link
    ports:
      - 8080
    depends_on:
      - grpc

  grpc:
    image: attend_manager_grpc
    build:
      context: .
      dockerfile: ./grpc/Dockerfile
    volumes:
      - ./:/go/app
      - ${PWD}/resource/gcp/dev/:/gcp/
    networks:
      - api-link
      - db-link
    ports:
      - 50051:50051
    env_file: ./grpc/.env
    depends_on:
      - "mysql"

  mysql:
    image: mysql
    build:
      context: .
      dockerfile: ./resource/mysql/Dockerfile
    volumes:
      - mysql-data:/var/lib/mysql
      - ./resource/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_DATABASE: attend
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      TZ: Asia/Tokyo
    networks:
      - db-link
    ports:
      - "3306:3306"

networks:
  default:
    external:
      name: bridge
  front-link:
    driver: bridge
  api-link:
    driver: bridge
  db-link:
    driver: bridge

volumes:
  mysql-data:
  vhost:
