version: '3.4'

services:
  api:
    image: attend_manager_api
    build:
      context: .
      dockerfile: ./api/Dockerfile
    volumes:
      - ./:/go/app
    networks:
      - container-link
    ports:
      - 8080:8080
  grpc:
    image: attend_manager_grpc
    build:
      context: .
      dockerfile: ./grpc/Dockerfile
    volumes:
      - ./:/go/app
    networks:
      - container-link
    ports:
      - 50051:50051
    links:
      - "mysql"
  mysql:
    image: mysql
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_DATABASE: attend
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      TZ: Asia/Tokyo
    networks:
      - container-link
    ports:
      - "3306:3306"

networks:
  default:
    external:
      name: bridge
  container-link:
    driver: bridge

volumes:
  mysql-data: