version: '3.4'

services:
  api:
    image: attend_manager_api
    build:
      context: .
      dockerfile: ./api/Dockerfile
    volumes:
      - ./:/go/app
    networks:
      - api-link
    ports:
      - 8080:8080
      depends_on:
        - grpc

  grpc:
    image: attend_manager_grpc
    build:
      context: .
      dockerfile: ./grpc/Dockerfile
    volumes:
      - ./:/go/app
    networks:
      - api-link
      - db-link
    ports:
      - 50051:50051
    depends_on:
      - "mysql"

  mysql:
    image: mysql
    build:
      context: .
      dockerfile: ./resource/mysql/Dockerfile
    volumes:
      - mysql-data:/var/lib/mysql
      - ./resource/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_DATABASE: attend
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      TZ: Asia/Tokyo
    networks:
      - db-link
    ports:
      - "3306:3306"

  migrate:
    image: migrate/migrate
    networks:
      - db-link
    volumes:
      - ./resource/mysql/migrations:/migrations
    command: ["-path", "/migrations", "-database",  "mysql://root:root@tcp(mysql:3306)/attend?query", "up", "3"]

networks:
  default:
    external:
      name: bridge
  api-link:
    driver: bridge
  db-link:
    driver: bridge

volumes:
  mysql-data: