GET https://api.attend-manager.localhost/healthcheck
###

POST https://api.attend-manager.localhost/user/register

{
    "group_id": "btvhepsodn8uvn791hrg",
    "login_id": "sample",
    "password": "fugahoge",
    "name": "hoge"
}