GET https://api.attend-manager.localhost/healthcheck
###

POST https://api.attend-manager.localhost/user/register

{
    "group_id": "btvhepsodn8uvn791hrg",
    "login_id": "sample",
    "password": "fugahoge",
    "name": "hoge"
}
###

POST https://api.attend-manager.localhost/group/create

{
    "name": "hoge",
    "login_id": "sample",
    "password": "fugahoge",
    "user_name": "btvhepsodn8uvn791hrg"
}

###

POST https://api.attend-manager.localhost/user/signin

{
    "group_name": "hoge",
    "login_id": "sample",
    "password": "fugahoge"
}