// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: grpc/proto/attendance_group.proto

package proto

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type AttendanceGroupRequesut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupName string `protobuf:"bytes,1,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	LoginId   string `protobuf:"bytes,2,opt,name=login_id,json=loginId,proto3" json:"login_id,omitempty"`
	Password  string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	UserName  string `protobuf:"bytes,4,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
}

func (x *AttendanceGroupRequesut) Reset() {
	*x = AttendanceGroupRequesut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_attendance_group_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttendanceGroupRequesut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttendanceGroupRequesut) ProtoMessage() {}

func (x *AttendanceGroupRequesut) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_attendance_group_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttendanceGroupRequesut.ProtoReflect.Descriptor instead.
func (*AttendanceGroupRequesut) Descriptor() ([]byte, []int) {
	return file_grpc_proto_attendance_group_proto_rawDescGZIP(), []int{0}
}

func (x *AttendanceGroupRequesut) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *AttendanceGroupRequesut) GetLoginId() string {
	if x != nil {
		return x.LoginId
	}
	return ""
}

func (x *AttendanceGroupRequesut) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *AttendanceGroupRequesut) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type AttendanceGroupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AttendanceGroupResponse) Reset() {
	*x = AttendanceGroupResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_attendance_group_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttendanceGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttendanceGroupResponse) ProtoMessage() {}

func (x *AttendanceGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_attendance_group_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttendanceGroupResponse.ProtoReflect.Descriptor instead.
func (*AttendanceGroupResponse) Descriptor() ([]byte, []int) {
	return file_grpc_proto_attendance_group_proto_rawDescGZIP(), []int{1}
}

var File_grpc_proto_attendance_group_proto protoreflect.FileDescriptor

var file_grpc_proto_attendance_group_proto_rawDesc = []byte{
	0x0a, 0x21, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x74, 0x74,
	0x65, 0x6e, 0x64, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8c, 0x01, 0x0a, 0x17, 0x41,
	0x74, 0x74, 0x65, 0x6e, 0x64, 0x61, 0x6e, 0x63, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x75, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x49, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x1b, 0x0a, 0x09,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x19, 0x0a, 0x17, 0x41, 0x74, 0x74,
	0x65, 0x6e, 0x64, 0x61, 0x6e, 0x63, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x32, 0x5d, 0x0a, 0x0f, 0x41, 0x74, 0x74, 0x65, 0x6e, 0x64, 0x61, 0x6e,
	0x63, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x4a, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x12, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x74, 0x74, 0x65, 0x6e, 0x64,
	0x61, 0x6e, 0x63, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x75,
	0x74, 0x1a, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x74, 0x74, 0x65, 0x6e, 0x64,
	0x61, 0x6e, 0x63, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_proto_attendance_group_proto_rawDescOnce sync.Once
	file_grpc_proto_attendance_group_proto_rawDescData = file_grpc_proto_attendance_group_proto_rawDesc
)

func file_grpc_proto_attendance_group_proto_rawDescGZIP() []byte {
	file_grpc_proto_attendance_group_proto_rawDescOnce.Do(func() {
		file_grpc_proto_attendance_group_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_proto_attendance_group_proto_rawDescData)
	})
	return file_grpc_proto_attendance_group_proto_rawDescData
}

var file_grpc_proto_attendance_group_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grpc_proto_attendance_group_proto_goTypes = []interface{}{
	(*AttendanceGroupRequesut)(nil), // 0: proto.AttendanceGroupRequesut
	(*AttendanceGroupResponse)(nil), // 1: proto.AttendanceGroupResponse
}
var file_grpc_proto_attendance_group_proto_depIdxs = []int32{
	0, // 0: proto.AttendanceGroup.Create:input_type -> proto.AttendanceGroupRequesut
	1, // 1: proto.AttendanceGroup.Create:output_type -> proto.AttendanceGroupResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_proto_attendance_group_proto_init() }
func file_grpc_proto_attendance_group_proto_init() {
	if File_grpc_proto_attendance_group_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_proto_attendance_group_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AttendanceGroupRequesut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_proto_attendance_group_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AttendanceGroupResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_proto_attendance_group_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_proto_attendance_group_proto_goTypes,
		DependencyIndexes: file_grpc_proto_attendance_group_proto_depIdxs,
		MessageInfos:      file_grpc_proto_attendance_group_proto_msgTypes,
	}.Build()
	File_grpc_proto_attendance_group_proto = out.File
	file_grpc_proto_attendance_group_proto_rawDesc = nil
	file_grpc_proto_attendance_group_proto_goTypes = nil
	file_grpc_proto_attendance_group_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AttendanceGroupClient is the client API for AttendanceGroup service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AttendanceGroupClient interface {
	Create(ctx context.Context, in *AttendanceGroupRequesut, opts ...grpc.CallOption) (*AttendanceGroupResponse, error)
}

type attendanceGroupClient struct {
	cc grpc.ClientConnInterface
}

func NewAttendanceGroupClient(cc grpc.ClientConnInterface) AttendanceGroupClient {
	return &attendanceGroupClient{cc}
}

func (c *attendanceGroupClient) Create(ctx context.Context, in *AttendanceGroupRequesut, opts ...grpc.CallOption) (*AttendanceGroupResponse, error) {
	out := new(AttendanceGroupResponse)
	err := c.cc.Invoke(ctx, "/proto.AttendanceGroup/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AttendanceGroupServer is the server API for AttendanceGroup service.
type AttendanceGroupServer interface {
	Create(context.Context, *AttendanceGroupRequesut) (*AttendanceGroupResponse, error)
}

// UnimplementedAttendanceGroupServer can be embedded to have forward compatible implementations.
type UnimplementedAttendanceGroupServer struct {
}

func (*UnimplementedAttendanceGroupServer) Create(context.Context, *AttendanceGroupRequesut) (*AttendanceGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}

func RegisterAttendanceGroupServer(s *grpc.Server, srv AttendanceGroupServer) {
	s.RegisterService(&_AttendanceGroup_serviceDesc, srv)
}

func _AttendanceGroup_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttendanceGroupRequesut)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttendanceGroupServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AttendanceGroup/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttendanceGroupServer).Create(ctx, req.(*AttendanceGroupRequesut))
	}
	return interceptor(ctx, in, info, handler)
}

var _AttendanceGroup_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AttendanceGroup",
	HandlerType: (*AttendanceGroupServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _AttendanceGroup_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/proto/attendance_group.proto",
}
