// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"errors"
	"fmt"
	"math"

	"github.com/facebook/ent/dialect/sql"
	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
	"github.com/rs/xid"
	"github.com/shoma-www/attend_manager/grpc/ent/attendancegroup"
	"github.com/shoma-www/attend_manager/grpc/ent/predicate"
	"github.com/shoma-www/attend_manager/grpc/ent/user"
)

// AttendanceGroupQuery is the builder for querying AttendanceGroup entities.
type AttendanceGroupQuery struct {
	config
	limit      *int
	offset     *int
	order      []OrderFunc
	unique     []string
	predicates []predicate.AttendanceGroup
	// eager-loading edges.
	withUsers *UserQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the builder.
func (agq *AttendanceGroupQuery) Where(ps ...predicate.AttendanceGroup) *AttendanceGroupQuery {
	agq.predicates = append(agq.predicates, ps...)
	return agq
}

// Limit adds a limit step to the query.
func (agq *AttendanceGroupQuery) Limit(limit int) *AttendanceGroupQuery {
	agq.limit = &limit
	return agq
}

// Offset adds an offset step to the query.
func (agq *AttendanceGroupQuery) Offset(offset int) *AttendanceGroupQuery {
	agq.offset = &offset
	return agq
}

// Order adds an order step to the query.
func (agq *AttendanceGroupQuery) Order(o ...OrderFunc) *AttendanceGroupQuery {
	agq.order = append(agq.order, o...)
	return agq
}

// QueryUsers chains the current query on the users edge.
func (agq *AttendanceGroupQuery) QueryUsers() *UserQuery {
	query := &UserQuery{config: agq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := agq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(attendancegroup.Table, attendancegroup.FieldID, agq.sqlQuery()),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, attendancegroup.UsersTable, attendancegroup.UsersColumn),
		)
		fromU = sqlgraph.SetNeighbors(agq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first AttendanceGroup entity in the query. Returns *NotFoundError when no attendancegroup was found.
func (agq *AttendanceGroupQuery) First(ctx context.Context) (*AttendanceGroup, error) {
	ags, err := agq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(ags) == 0 {
		return nil, &NotFoundError{attendancegroup.Label}
	}
	return ags[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (agq *AttendanceGroupQuery) FirstX(ctx context.Context) *AttendanceGroup {
	ag, err := agq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return ag
}

// FirstID returns the first AttendanceGroup id in the query. Returns *NotFoundError when no id was found.
func (agq *AttendanceGroupQuery) FirstID(ctx context.Context) (id xid.ID, err error) {
	var ids []xid.ID
	if ids, err = agq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{attendancegroup.Label}
		return
	}
	return ids[0], nil
}

// FirstXID is like FirstID, but panics if an error occurs.
func (agq *AttendanceGroupQuery) FirstXID(ctx context.Context) xid.ID {
	id, err := agq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns the only AttendanceGroup entity in the query, returns an error if not exactly one entity was returned.
func (agq *AttendanceGroupQuery) Only(ctx context.Context) (*AttendanceGroup, error) {
	ags, err := agq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(ags) {
	case 1:
		return ags[0], nil
	case 0:
		return nil, &NotFoundError{attendancegroup.Label}
	default:
		return nil, &NotSingularError{attendancegroup.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (agq *AttendanceGroupQuery) OnlyX(ctx context.Context) *AttendanceGroup {
	ag, err := agq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return ag
}

// OnlyID returns the only AttendanceGroup id in the query, returns an error if not exactly one id was returned.
func (agq *AttendanceGroupQuery) OnlyID(ctx context.Context) (id xid.ID, err error) {
	var ids []xid.ID
	if ids, err = agq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{attendancegroup.Label}
	default:
		err = &NotSingularError{attendancegroup.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (agq *AttendanceGroupQuery) OnlyIDX(ctx context.Context) xid.ID {
	id, err := agq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AttendanceGroups.
func (agq *AttendanceGroupQuery) All(ctx context.Context) ([]*AttendanceGroup, error) {
	if err := agq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return agq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (agq *AttendanceGroupQuery) AllX(ctx context.Context) []*AttendanceGroup {
	ags, err := agq.All(ctx)
	if err != nil {
		panic(err)
	}
	return ags
}

// IDs executes the query and returns a list of AttendanceGroup ids.
func (agq *AttendanceGroupQuery) IDs(ctx context.Context) ([]xid.ID, error) {
	var ids []xid.ID
	if err := agq.Select(attendancegroup.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (agq *AttendanceGroupQuery) IDsX(ctx context.Context) []xid.ID {
	ids, err := agq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (agq *AttendanceGroupQuery) Count(ctx context.Context) (int, error) {
	if err := agq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return agq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (agq *AttendanceGroupQuery) CountX(ctx context.Context) int {
	count, err := agq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (agq *AttendanceGroupQuery) Exist(ctx context.Context) (bool, error) {
	if err := agq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return agq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (agq *AttendanceGroupQuery) ExistX(ctx context.Context) bool {
	exist, err := agq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the query builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (agq *AttendanceGroupQuery) Clone() *AttendanceGroupQuery {
	return &AttendanceGroupQuery{
		config:     agq.config,
		limit:      agq.limit,
		offset:     agq.offset,
		order:      append([]OrderFunc{}, agq.order...),
		unique:     append([]string{}, agq.unique...),
		predicates: append([]predicate.AttendanceGroup{}, agq.predicates...),
		// clone intermediate query.
		sql:  agq.sql.Clone(),
		path: agq.path,
	}
}

//  WithUsers tells the query-builder to eager-loads the nodes that are connected to
// the "users" edge. The optional arguments used to configure the query builder of the edge.
func (agq *AttendanceGroupQuery) WithUsers(opts ...func(*UserQuery)) *AttendanceGroupQuery {
	query := &UserQuery{config: agq.config}
	for _, opt := range opts {
		opt(query)
	}
	agq.withUsers = query
	return agq
}

// GroupBy used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"Name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AttendanceGroup.Query().
//		GroupBy(attendancegroup.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (agq *AttendanceGroupQuery) GroupBy(field string, fields ...string) *AttendanceGroupGroupBy {
	group := &AttendanceGroupGroupBy{config: agq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := agq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return agq.sqlQuery(), nil
	}
	return group
}

// Select one or more fields from the given query.
//
// Example:
//
//	var v []struct {
//		Name string `json:"Name,omitempty"`
//	}
//
//	client.AttendanceGroup.Query().
//		Select(attendancegroup.FieldName).
//		Scan(ctx, &v)
//
func (agq *AttendanceGroupQuery) Select(field string, fields ...string) *AttendanceGroupSelect {
	selector := &AttendanceGroupSelect{config: agq.config}
	selector.fields = append([]string{field}, fields...)
	selector.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := agq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return agq.sqlQuery(), nil
	}
	return selector
}

func (agq *AttendanceGroupQuery) prepareQuery(ctx context.Context) error {
	if agq.path != nil {
		prev, err := agq.path(ctx)
		if err != nil {
			return err
		}
		agq.sql = prev
	}
	return nil
}

func (agq *AttendanceGroupQuery) sqlAll(ctx context.Context) ([]*AttendanceGroup, error) {
	var (
		nodes       = []*AttendanceGroup{}
		_spec       = agq.querySpec()
		loadedTypes = [1]bool{
			agq.withUsers != nil,
		}
	)
	_spec.ScanValues = func() []interface{} {
		node := &AttendanceGroup{config: agq.config}
		nodes = append(nodes, node)
		values := node.scanValues()
		return values
	}
	_spec.Assign = func(values ...interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(values...)
	}
	if err := sqlgraph.QueryNodes(ctx, agq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := agq.withUsers; query != nil {
		fks := make([]driver.Value, 0, len(nodes))
		nodeids := make(map[xid.ID]*AttendanceGroup)
		for i := range nodes {
			fks = append(fks, nodes[i].ID)
			nodeids[nodes[i].ID] = nodes[i]
		}
		query.withFKs = true
		query.Where(predicate.User(func(s *sql.Selector) {
			s.Where(sql.InValues(attendancegroup.UsersColumn, fks...))
		}))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			fk := n.attendance_group_users
			if fk == nil {
				return nil, fmt.Errorf(`foreign-key "attendance_group_users" is nil for node %v`, n.ID)
			}
			node, ok := nodeids[*fk]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "attendance_group_users" returned %v for node %v`, *fk, n.ID)
			}
			node.Edges.Users = append(node.Edges.Users, n)
		}
	}

	return nodes, nil
}

func (agq *AttendanceGroupQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := agq.querySpec()
	return sqlgraph.CountNodes(ctx, agq.driver, _spec)
}

func (agq *AttendanceGroupQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := agq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %v", err)
	}
	return n > 0, nil
}

func (agq *AttendanceGroupQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   attendancegroup.Table,
			Columns: attendancegroup.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: attendancegroup.FieldID,
			},
		},
		From:   agq.sql,
		Unique: true,
	}
	if ps := agq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := agq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := agq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := agq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (agq *AttendanceGroupQuery) sqlQuery() *sql.Selector {
	builder := sql.Dialect(agq.driver.Dialect())
	t1 := builder.Table(attendancegroup.Table)
	selector := builder.Select(t1.Columns(attendancegroup.Columns...)...).From(t1)
	if agq.sql != nil {
		selector = agq.sql
		selector.Select(selector.Columns(attendancegroup.Columns...)...)
	}
	for _, p := range agq.predicates {
		p(selector)
	}
	for _, p := range agq.order {
		p(selector)
	}
	if offset := agq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := agq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AttendanceGroupGroupBy is the builder for group-by AttendanceGroup entities.
type AttendanceGroupGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (aggb *AttendanceGroupGroupBy) Aggregate(fns ...AggregateFunc) *AttendanceGroupGroupBy {
	aggb.fns = append(aggb.fns, fns...)
	return aggb
}

// Scan applies the group-by query and scan the result into the given value.
func (aggb *AttendanceGroupGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := aggb.path(ctx)
	if err != nil {
		return err
	}
	aggb.sql = query
	return aggb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (aggb *AttendanceGroupGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := aggb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by. It is only allowed when querying group-by with one field.
func (aggb *AttendanceGroupGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(aggb.fields) > 1 {
		return nil, errors.New("ent: AttendanceGroupGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := aggb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (aggb *AttendanceGroupGroupBy) StringsX(ctx context.Context) []string {
	v, err := aggb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from group-by. It is only allowed when querying group-by with one field.
func (aggb *AttendanceGroupGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = aggb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{attendancegroup.Label}
	default:
		err = fmt.Errorf("ent: AttendanceGroupGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (aggb *AttendanceGroupGroupBy) StringX(ctx context.Context) string {
	v, err := aggb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by. It is only allowed when querying group-by with one field.
func (aggb *AttendanceGroupGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(aggb.fields) > 1 {
		return nil, errors.New("ent: AttendanceGroupGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := aggb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (aggb *AttendanceGroupGroupBy) IntsX(ctx context.Context) []int {
	v, err := aggb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from group-by. It is only allowed when querying group-by with one field.
func (aggb *AttendanceGroupGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = aggb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{attendancegroup.Label}
	default:
		err = fmt.Errorf("ent: AttendanceGroupGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (aggb *AttendanceGroupGroupBy) IntX(ctx context.Context) int {
	v, err := aggb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by. It is only allowed when querying group-by with one field.
func (aggb *AttendanceGroupGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(aggb.fields) > 1 {
		return nil, errors.New("ent: AttendanceGroupGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := aggb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (aggb *AttendanceGroupGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := aggb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from group-by. It is only allowed when querying group-by with one field.
func (aggb *AttendanceGroupGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = aggb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{attendancegroup.Label}
	default:
		err = fmt.Errorf("ent: AttendanceGroupGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (aggb *AttendanceGroupGroupBy) Float64X(ctx context.Context) float64 {
	v, err := aggb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by. It is only allowed when querying group-by with one field.
func (aggb *AttendanceGroupGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(aggb.fields) > 1 {
		return nil, errors.New("ent: AttendanceGroupGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := aggb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (aggb *AttendanceGroupGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := aggb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from group-by. It is only allowed when querying group-by with one field.
func (aggb *AttendanceGroupGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = aggb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{attendancegroup.Label}
	default:
		err = fmt.Errorf("ent: AttendanceGroupGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (aggb *AttendanceGroupGroupBy) BoolX(ctx context.Context) bool {
	v, err := aggb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (aggb *AttendanceGroupGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := aggb.sqlQuery().Query()
	if err := aggb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (aggb *AttendanceGroupGroupBy) sqlQuery() *sql.Selector {
	selector := aggb.sql
	columns := make([]string, 0, len(aggb.fields)+len(aggb.fns))
	columns = append(columns, aggb.fields...)
	for _, fn := range aggb.fns {
		columns = append(columns, fn(selector))
	}
	return selector.Select(columns...).GroupBy(aggb.fields...)
}

// AttendanceGroupSelect is the builder for select fields of AttendanceGroup entities.
type AttendanceGroupSelect struct {
	config
	fields []string
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Scan applies the selector query and scan the result into the given value.
func (ags *AttendanceGroupSelect) Scan(ctx context.Context, v interface{}) error {
	query, err := ags.path(ctx)
	if err != nil {
		return err
	}
	ags.sql = query
	return ags.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (ags *AttendanceGroupSelect) ScanX(ctx context.Context, v interface{}) {
	if err := ags.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from selector. It is only allowed when selecting one field.
func (ags *AttendanceGroupSelect) Strings(ctx context.Context) ([]string, error) {
	if len(ags.fields) > 1 {
		return nil, errors.New("ent: AttendanceGroupSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := ags.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (ags *AttendanceGroupSelect) StringsX(ctx context.Context) []string {
	v, err := ags.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from selector. It is only allowed when selecting one field.
func (ags *AttendanceGroupSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = ags.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{attendancegroup.Label}
	default:
		err = fmt.Errorf("ent: AttendanceGroupSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (ags *AttendanceGroupSelect) StringX(ctx context.Context) string {
	v, err := ags.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from selector. It is only allowed when selecting one field.
func (ags *AttendanceGroupSelect) Ints(ctx context.Context) ([]int, error) {
	if len(ags.fields) > 1 {
		return nil, errors.New("ent: AttendanceGroupSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := ags.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (ags *AttendanceGroupSelect) IntsX(ctx context.Context) []int {
	v, err := ags.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from selector. It is only allowed when selecting one field.
func (ags *AttendanceGroupSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = ags.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{attendancegroup.Label}
	default:
		err = fmt.Errorf("ent: AttendanceGroupSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (ags *AttendanceGroupSelect) IntX(ctx context.Context) int {
	v, err := ags.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from selector. It is only allowed when selecting one field.
func (ags *AttendanceGroupSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(ags.fields) > 1 {
		return nil, errors.New("ent: AttendanceGroupSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := ags.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (ags *AttendanceGroupSelect) Float64sX(ctx context.Context) []float64 {
	v, err := ags.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from selector. It is only allowed when selecting one field.
func (ags *AttendanceGroupSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = ags.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{attendancegroup.Label}
	default:
		err = fmt.Errorf("ent: AttendanceGroupSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (ags *AttendanceGroupSelect) Float64X(ctx context.Context) float64 {
	v, err := ags.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from selector. It is only allowed when selecting one field.
func (ags *AttendanceGroupSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(ags.fields) > 1 {
		return nil, errors.New("ent: AttendanceGroupSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := ags.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (ags *AttendanceGroupSelect) BoolsX(ctx context.Context) []bool {
	v, err := ags.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from selector. It is only allowed when selecting one field.
func (ags *AttendanceGroupSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = ags.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{attendancegroup.Label}
	default:
		err = fmt.Errorf("ent: AttendanceGroupSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (ags *AttendanceGroupSelect) BoolX(ctx context.Context) bool {
	v, err := ags.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ags *AttendanceGroupSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := ags.sqlQuery().Query()
	if err := ags.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (ags *AttendanceGroupSelect) sqlQuery() sql.Querier {
	selector := ags.sql
	selector.Select(selector.Columns(ags.fields...)...)
	return selector
}
