// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebook/ent/dialect/sql"
	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
	"github.com/shoma-www/attend_manager/grpc/ent/attendancegroup"
	"github.com/shoma-www/attend_manager/grpc/ent/predicate"
)

// AttendanceGroupDelete is the builder for deleting a AttendanceGroup entity.
type AttendanceGroupDelete struct {
	config
	hooks      []Hook
	mutation   *AttendanceGroupMutation
	predicates []predicate.AttendanceGroup
}

// Where adds a new predicate to the delete builder.
func (agd *AttendanceGroupDelete) Where(ps ...predicate.AttendanceGroup) *AttendanceGroupDelete {
	agd.predicates = append(agd.predicates, ps...)
	return agd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (agd *AttendanceGroupDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(agd.hooks) == 0 {
		affected, err = agd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AttendanceGroupMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			agd.mutation = mutation
			affected, err = agd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(agd.hooks) - 1; i >= 0; i-- {
			mut = agd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, agd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (agd *AttendanceGroupDelete) ExecX(ctx context.Context) int {
	n, err := agd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (agd *AttendanceGroupDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: attendancegroup.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: attendancegroup.FieldID,
			},
		},
	}
	if ps := agd.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, agd.driver, _spec)
}

// AttendanceGroupDeleteOne is the builder for deleting a single AttendanceGroup entity.
type AttendanceGroupDeleteOne struct {
	agd *AttendanceGroupDelete
}

// Exec executes the deletion query.
func (agdo *AttendanceGroupDeleteOne) Exec(ctx context.Context) error {
	n, err := agdo.agd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{attendancegroup.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (agdo *AttendanceGroupDeleteOne) ExecX(ctx context.Context) {
	agdo.agd.ExecX(ctx)
}
