// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/shoma-www/attend_manager/grpc/ent/attendancegroup"
	"github.com/shoma-www/attend_manager/grpc/ent/schema"
	"github.com/shoma-www/attend_manager/grpc/ent/user"
)

// The init function reads all schema descriptors with runtime
// code (default values, validators or hooks) and stitches it
// to their package variables.
func init() {
	attendancegroupFields := schema.AttendanceGroup{}.Fields()
	_ = attendancegroupFields
	// attendancegroupDescName is the schema descriptor for Name field.
	attendancegroupDescName := attendancegroupFields[1].Descriptor()
	// attendancegroup.NameValidator is a validator for the "Name" field. It is called by the builders before save.
	attendancegroup.NameValidator = attendancegroupDescName.Validators[0].(func(string) error)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescLoginID is the schema descriptor for LoginID field.
	userDescLoginID := userFields[1].Descriptor()
	// user.LoginIDValidator is a validator for the "LoginID" field. It is called by the builders before save.
	user.LoginIDValidator = func() func(string) error {
		validators := userDescLoginID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(_LoginID string) error {
			for _, fn := range fns {
				if err := fn(_LoginID); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescPassword is the schema descriptor for Password field.
	userDescPassword := userFields[2].Descriptor()
	// user.PasswordValidator is a validator for the "Password" field. It is called by the builders before save.
	user.PasswordValidator = func() func(string) error {
		validators := userDescPassword.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(_Password string) error {
			for _, fn := range fns {
				if err := fn(_Password); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescName is the schema descriptor for Name field.
	userDescName := userFields[3].Descriptor()
	// user.NameValidator is a validator for the "Name" field. It is called by the builders before save.
	user.NameValidator = userDescName.Validators[0].(func(string) error)
}
